const quotes = [
  "This blog is proudly not powered by Wordpress.",
  "タイガー、ファイヤー、サイバー、ファイバー、ダイバー、バイバー、ジャージャー！",
  "Ai! Katsu! Ai! Katsu!",
  "lol random quotes",
  "&quot;ヲタ芸 is just Japanese Zumba&quot;",
  "Are you READY? I'M L@DY!",
  "To performers, these cards are life itself.",
  "You gotta BELIEVE!",
  "ayy lmao",
  "オケオケオッケー！",
  "&quot;; DROP TABLE `blog`;--",
  "&lt;?php echo $randomquote; ?&gt;",
  "&lt;script&gt;document.write(randomQuote)&lt;/script&gt;",
  "Takane is best idol",
  "Konomi is best idol",
  "Idolmaster Kotori is best idol",
  "Ichigo is best idol",
  "Creamy Mami is best idol",
  "oats curry summer",
  "~~~!KAWAII!~~~",
  "I CAN'T STOP CRYING... BUCKETS OF TEARS!",
  "Reality Check!",
  "Dojo... Casino... It's all in the mind",
  "I wonder what's for dinner...",
  "SHE IS MY WIFE",
  "IIDX GOOOOOOOOLD!!!",
  "くっ！",
  "Never Gonna Give You Up",
  "Never Gonna Let You Down",
  "If you believe it, you can be somebody",
  "For those mentally 18 and up",
  "Anyone up for Scrabble later?",
  "LOL IM SUCH AN OTAKU!!!!~~ XDDDD",
  "how do u hold the bar?",
  "Final Destination. No Items. Fox Only.",
  "Shijou Shijou!",
  "Rippin' bro, you cleared it!",
  "Reticulating Splines",
  "Selamat Pagi!",
  "No Cutting Corners!",
  "Here I come, Constantinople!",
  "WELCOME TO DIE",
  "~Juicy Party~",
  "spoopy",
  "afuuu",
  "PRESENT DAY... PRESENT TIME!",
  "tehe",
  "Produced by Tachibana Labs",
  "Hip hop hippy hippy hippy hop hippy hop you don't stop",
  "My name is Inigo Montoya. You killed my father. Prepare to die.",
  "FRIED CHICKEN!!!",
  "Need a dispenser here",
  "Fast 'n Bulbous!",
  "CHUNKY BACON!",
  "Why do you need Konami original songs?",
  "And them's the facts",
  "You work, You lose",
  "Is Guava a Donut?",
  "The More You Know...",
  "WHAT A HORRIBLE NIGHT TO HAVE A CURSE",
  "xyzzy",
  "Would you like Bemani?",
  "WHO ARE YOU RUNNING FROM?",
  "アイマス最高！",
  "I'm a psycho!",
  "明日があるさ。",
  "I see you shiver with antici...",
  "Stay fresh!",
  "Remember, licking doorknobs is illegal on other planets",
  "YOU GIVE LOVE A BAD NAME!",
  "^C^C^C^[^[^Cqquit",
  "The Residents are practically Japanese, but no one knows.",
  "ロックだねー！",
  "クルクルキャワワ~",
  "We did not invent the algorithm. The algorithm consistently finds Jesus. The algorithm killed Jeeves.",
  "My socks! I can't move my socks!",
  "...PATION!",
  "ENCORE! ENCORE!",
  "Let's do the Time Warp again!",
  "Segmentation Fault (core dumped)",
  "Sunday Monday Chu Chu Tuesday",
  "She doesn't even go here!",
  "Where we're going, we don't need roads",
  ":3",
  "What is a man but a miserable pile of secrets?",
  "I wonder how these random quotes affect this blog's SEO",
  "This blog is proudly not powered by Blogger.",
  "This blog is proudly not powered by Tumblr.",
  "This blog is proudly not powered by Drupal.",
  "This blog is proudly not powered by PHP.",
  "This blog is proudly not powered by Angular.",
  "GET HYPE",
  "[insert meme here]",
  "All is going according to 計画",
  "You're the cream of the crop, baby!",
  "C'mon... look into my eyes...",
  "SHOT THROUGH THE ART AND YOU'RE TO FRAME",
  "To show or to be shown?",
  "Do a barrel roll! (Press R or Z twice)",
  "Istanbul, not Constantinople",
  "Identify possessions? y/n/q",
  "A footer for people with no budget for FX",
  "yeah this if you think there should be a pants shop!!!!",
  "Burma Shave",
  "correct horse battery staple",
  "You know what they say: All toasters toast toast!",
  "egregiously",
  "Welcome to the Blogosphere!",
  "Galactic conquest is here!",
  "TENSION MAX!",
  "Tension relax!",
  "what if idols were real",
  "穏やかじゃない！",
  "NOT ODAYAKA",
  "Exiting the forest is super simple, all you do is follow these path turns.",
  "This blog is proudly not powered by ConMagick",
  "熱い！～",
  "How can idols be real if our eyes aren't real?",
  "&lt;/765&gt;",
  "Do you ever... wonder who you are?",
  "You READY-OKEY?!",
  "Please understand",
  "According to all known laws of aviation...",
  "whoa",
  "Phrasing!",
  "amogus",
  "I am sitting here eating a bacon cheeseburger with TWO PATTIES!!!",
  "Daily reminder that once they made a show about the GEICO cavemen. I mean... wow... remember THAT?",
  "Aurora borealis!? At this time of year, at this time of day, on this operating system, localized entirely within the footer of this blog???",
  "PLAY FREE BIRD! PLEASE PLAY FREE BIRD!!!",
  "EISAI! HARAMASUKOI!",
  "MAAAN, I'M NOT PART OF YOUR SYSTEM!",
  "食べないでください！",
  "Does anyone want some roses?",
  "It's just like, it's just like, a mini JAPAN",
  "D E F G E C D",
  "Happy Lucky!",
  "みあが一番！",
  "バーニング！！！！！",
  "それ…アイカツか？",
  "システムです！",
  "かしこまっ！",
  "ding dong bing bong",
  "DROP THE GUN MEG",
  "10 YEARS OOOOOLD",
  'Don\'t you just love the word "potato"?',
  "スキスキ",
  "あ！",
  "memo memo",
  "Rum Raisin!",
  "グラシアス！つまり、ありがとう",
  "John Mastodon",
  "メルヘ～ン！",
  "Stitch! From Lilo and Stitch!",
  "Duolingo here! Do your language practice or we'll fucking kill you",
  "kyupikon",
  "They say the moon is made of cheese. I wonder if there's any rats up there.",
  "Da Vinci",
  "なちゅ～",
  "DA VINKY?",
  "It's Morbin' Time",
];

function generateRandomQuote() {
  const quoteDiv = document.getElementById("random-quote");
  if (quoteDiv) {
    const quote = quotes[Math.floor(Math.random() * quotes.length)];
    quoteDiv.innerHTML = quote;
  }
}

document.addEventListener("DOMContentLoaded", () => {
  (window as any).generateRandomQuote = generateRandomQuote;
  const backgrounds = [
    "starlight_dorm.png",
    "starlight_gakuen2.png",
    "starlight_gakuen3.png",
    "starlight_gakuen.png",
    "starlight_koko.png",
    "starlight_queen.png",
    "starlight_sunset.png",
  ];
  const bg = backgrounds[Math.floor(Math.random() * backgrounds.length)];
  const darkmode = ["starlight_dorm.png", "starlight_gakuen3.png"];
  let cover = "cover_bg_saturnmode-light.png";
  if (darkmode.includes(bg)) {
    cover = "cover_bg_saturnmode.png";
  }
  const base = (window as any).baseUrl ? (window as any).baseUrl + "/" : "";
  const header = document.getElementById("header");
  if (header) {
    header.style.backgroundImage = `url('${base}img/${bg}')`;
  }
  const logoCover = document.getElementById("logo-cover");
  if (logoCover) {
    logoCover.style.backgroundImage = `url('${base}img/${cover}')`;
  }
  generateRandomQuote();
});
