export const defaultCowSayings: string[] = [
  // From `fortune`'s computer files:
  'A hacker does for love what others would not do for money.',
  'All constants are variables.',
  'Another megabytes the dust.',
  'As a computer, I find your faith in technology amusing.',
  'Your fault -- core dumped',
  'Your password is pitifully obvious.',
  'Your code should be more efficient!',
  'Unix is a beast; its plural form is Unixen.',
  '* UNIX is a Trademark of Bell Laboratories.',
  'She sells cshs by the cshore.',
  'Row, row, row your bits, gently down the stream...',
  "RAM wasn't built in a day.",
  'Premature optimization is the root of all evil.',
  'It is now pitch dark.  If you proceed, you will likely fall into a pit.',
  'I wish you humans would leave me alone.',
  'I have not yet begun to byte!',
  'I came, I saw, I deleted all your files.',
  'fortune: not found',
  'fortune: No such file or directory',
  'FORTH IF HONK THEN',
  "Calm down, it's *only* ones and zeroes.",
  'Avoid the Gates of Hell.  Use Linux',
  'The easiest way to get the root password is to become system admin.',
  'LOAD "LINUX",8,1',
  'Colorless green ideas sleep furiously.',
  // From Bib Bop II:
  "Chlwah! I'm the most ultimate Ghost-Ball beast!",
  'Mooooo...',
  // From blog:
  '&lt;?php echo $randomquote; ?&gt;',
  'oats curry summer',
  "I CAN'T STOP CRYING... BUCKETS OF TEARS!",
  'Reality Check!',
  "Dojo... Casino... It's all in the mind",
  "I wonder what's for dinner...",
  'Never Gonna Give You Up',
  'Never Gonna Let You Down',
  'If you believe it, you can be somebody',
  'Anyone up for Scrabble later?',
  "Rippin' bro, you cleared it!",
  'Reticulating Splines',
  'Selamat Pagi!',
  'No Cutting Corners!',
  'Here I come, Constantinople!',
  'PRESENT DAY... PRESENT TIME!',
  'Produced by Tachibana Labs',
  'Need a dispenser here',
  "Fast 'n Bulbous!",
  'CHUNKY BACON!',
  'Why do you need Konami original songs?',
  'Is Guava a Donut?',
  'WHAT A HORRIBLE NIGHT TO HAVE A CURSE',
  'WHO ARE YOU RUNNING FROM?',
  'I see you shiver with antici...',
  'Stay fresh!',
  'Remember, licking doorknobs is illegal on other planets',
  '^C^C^C^[^[^Cqquit',
  '...PATION!',
  'What is a man but a miserable pile of secrets?',
  'To show or to be shown?',
  'Do a barrel roll! (Press R or Z twice)',
  'Istanbul, not Constantinople',
  'Kiss me, son of God!',
  'Welcome to the Blogosphere!',
  'Galactic conquest is here!',
  'TENSION MAX!',
  'Tension relax!',
  'NOT ODAYAKA',
  'Exiting the forest is super simple, all you do is follow these path turns.',
  'Please understand',
  'According to all known laws of aviation...',
  'amogus',
  'PLAY FREE BIRD! PLEASE PLAY FREE BIRD!!!',
  'EISAI! HARAMASUKOI!',
  "MAAAN, I'M NOT PART OF YOUR SYSTEM!",
  'Happy Lucky!',
  'ding dong bing bong',
  'Don\'t you just love the word "potato"?',
  'John Mastodon',
  'Stitch! From Lilo and Stitch!',
  'kyupikon',
  "It's Morbin' Time",
  "They say the moon is made of cheese. I wonder if there's any rats up there.",
  'Idol time is money!',
  'CPU time is money!',
  'Pirika Pirilala',
  'Aurora borealis!? At this time of year, at this time of day, on this website, localized entirely within this speech bubble???',
  "Are you READY? I'M L@DY!",
];

export const defaultCatClockSayings: string[] = [
  'Meowzers!',
  'This time is Doopee Time...',
  "Time isn't holding up! Time isn't after us!",
  'Ticking away the moments that make up a dull day',
  'Nya...',
  'Mew meow!',
  'Tick tock!',
  'Shout it out loud!',
];

export const defaultEyesSayings: string[] = ['What are YOU looking at?', 'I think I need glasses', 'Eye see you!'];

export const defaultAnyoneSayings: string[] = [
  'Now THIS is some engaging web content!',
  "It looks like you're trying to browse a website. Would you like help?",
  'Use RSS feeds!',
  'Delete your social media!',
  'Uninstall Windows!',
  "Make sure you're staying hydrated.",
  'Is this a dream?',
  "It's a UNIX system!",
  'Cancel your subscriptions!',
  'Where the heck is the start menu?',
];

export const defaultBiblicalSayings: string[] = [
  'BE NOT AFRAID',
  'WE ARE ONE',
  'WE THINK WE NEED GLASSES',
  'WE ARE WATCHING',
  'DO NOT MIND US, WE ARE JUST "HANGING OUT"',
  'THOU MUST USE RSS FEEDS',
  'DELETE THY SOCIAL MEDIA',
  'DISAVOW ONESELF FROM WINDOWS',
  'TIS A UNIX SYSTEM',
  'CANCEL THY SUBSCRIPTIONS',
];
