/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { IPrismStoneFeedItem } from "./components/mew151-prismstone-feed/prismstone-feed-item";
import { RssFeedProvider } from "./components/mew151-prismstone-feed/prismstone-feed-provider";
export { IPrismStoneFeedItem } from "./components/mew151-prismstone-feed/prismstone-feed-item";
export { RssFeedProvider } from "./components/mew151-prismstone-feed/prismstone-feed-provider";
export namespace Components {
    /**
     * Component for the Mew sprites on the Mew151.net homepage. This handles the logic to swap out the image with the "shiny" equivalent sprite if the user is lucky enough.
     */
    interface Mew151Mew {
        /**
          * Alt text to apply to the sprite.
          * @default ''
         */
        "alt": string;
        /**
          * RNG function to determine if the Mew sprite is Shiny
          * @default () => this.calculateShinyOdds()
         */
        "isShiny": () => boolean;
        /**
          * The image source to be passed in.
          * @default ''
         */
        "src": string;
    }
    /**
     * Renders my fediverse feed fetched from an RSS feed.
     */
    interface Mew151PrismstoneFeed {
        /**
          * The feed provider. This is mainly used for injecting a mock feed provider for testing.
          * @default new PrismStoneFeedProvider()
         */
        "feedProvider": RssFeedProvider;
        /**
          * Items to render. If not provided, then the component will fetch a feed with the default Prism Stone Feed Provider.
          * @default undefined
         */
        "items": IPrismStoneFeedItem[] | undefined;
    }
    /**
     * A cat clock, based on xclock's cat display mode.
     */
    interface Mew151XCatclock {
        /**
          * The color of the bowtie to display. Accepts any valid CSS colors, and possibly a few bonus ones.
          * @default '#a99cef'
         */
        "color": string;
    }
    /**
     * Renders cowsay in a "terminal"
     */
    interface Mew151XCowsay {
        /**
          * Replacement eyes for the cow
         */
        "eyes": string | undefined;
        /**
          * Replacement tongue for the cow
         */
        "mouth": string | undefined;
        /**
          * The text for the cow to say
          * @default 'Moo!'
         */
        "text": string;
    }
    /**
     * The main component that shows UNIX desktop toys on Mew151.net!
     */
    interface Mew151XRandom {
        /**
          * Odds of biblically accurate xeyes
          * @default 1 / 48
         */
        "biblicallyAccurateOdds": number;
        /**
          * Allows a page to force a specific desktop toy to appear
         */
        "forceSelection": ToyType | undefined;
        /**
          * Odds of getting a The Residents xeyes
          * @default 0
         */
        "residentOdds": number;
        /**
          * The color of the cat clock's tie
         */
        "tieColor": string | undefined;
    }
    interface Mew151XXeyes {
        /**
          * Whether the eyes are biblically accurate or not
          * @default false
         */
        "biblicallyAccurate": boolean;
        /**
          * The height of the canvas
         */
        "height": number;
        /**
          * Whether The Residents are watching or not
          * @default false
         */
        "theResidentsMode": boolean;
        /**
          * The width of the canvas
         */
        "width": number;
    }
}
declare global {
    /**
     * Component for the Mew sprites on the Mew151.net homepage. This handles the logic to swap out the image with the "shiny" equivalent sprite if the user is lucky enough.
     */
    interface HTMLMew151MewElement extends Components.Mew151Mew, HTMLStencilElement {
    }
    var HTMLMew151MewElement: {
        prototype: HTMLMew151MewElement;
        new (): HTMLMew151MewElement;
    };
    /**
     * Renders my fediverse feed fetched from an RSS feed.
     */
    interface HTMLMew151PrismstoneFeedElement extends Components.Mew151PrismstoneFeed, HTMLStencilElement {
    }
    var HTMLMew151PrismstoneFeedElement: {
        prototype: HTMLMew151PrismstoneFeedElement;
        new (): HTMLMew151PrismstoneFeedElement;
    };
    /**
     * A cat clock, based on xclock's cat display mode.
     */
    interface HTMLMew151XCatclockElement extends Components.Mew151XCatclock, HTMLStencilElement {
    }
    var HTMLMew151XCatclockElement: {
        prototype: HTMLMew151XCatclockElement;
        new (): HTMLMew151XCatclockElement;
    };
    /**
     * Renders cowsay in a "terminal"
     */
    interface HTMLMew151XCowsayElement extends Components.Mew151XCowsay, HTMLStencilElement {
    }
    var HTMLMew151XCowsayElement: {
        prototype: HTMLMew151XCowsayElement;
        new (): HTMLMew151XCowsayElement;
    };
    /**
     * The main component that shows UNIX desktop toys on Mew151.net!
     */
    interface HTMLMew151XRandomElement extends Components.Mew151XRandom, HTMLStencilElement {
    }
    var HTMLMew151XRandomElement: {
        prototype: HTMLMew151XRandomElement;
        new (): HTMLMew151XRandomElement;
    };
    interface HTMLMew151XXeyesElement extends Components.Mew151XXeyes, HTMLStencilElement {
    }
    var HTMLMew151XXeyesElement: {
        prototype: HTMLMew151XXeyesElement;
        new (): HTMLMew151XXeyesElement;
    };
    interface HTMLElementTagNameMap {
        "mew151-mew": HTMLMew151MewElement;
        "mew151-prismstone-feed": HTMLMew151PrismstoneFeedElement;
        "mew151-x-catclock": HTMLMew151XCatclockElement;
        "mew151-x-cowsay": HTMLMew151XCowsayElement;
        "mew151-x-random": HTMLMew151XRandomElement;
        "mew151-x-xeyes": HTMLMew151XXeyesElement;
    }
}
declare namespace LocalJSX {
    /**
     * Component for the Mew sprites on the Mew151.net homepage. This handles the logic to swap out the image with the "shiny" equivalent sprite if the user is lucky enough.
     */
    interface Mew151Mew {
        /**
          * Alt text to apply to the sprite.
          * @default ''
         */
        "alt"?: string;
        /**
          * RNG function to determine if the Mew sprite is Shiny
          * @default () => this.calculateShinyOdds()
         */
        "isShiny"?: () => boolean;
        /**
          * The image source to be passed in.
          * @default ''
         */
        "src"?: string;
    }
    /**
     * Renders my fediverse feed fetched from an RSS feed.
     */
    interface Mew151PrismstoneFeed {
        /**
          * The feed provider. This is mainly used for injecting a mock feed provider for testing.
          * @default new PrismStoneFeedProvider()
         */
        "feedProvider"?: RssFeedProvider;
        /**
          * Items to render. If not provided, then the component will fetch a feed with the default Prism Stone Feed Provider.
          * @default undefined
         */
        "items"?: IPrismStoneFeedItem[] | undefined;
    }
    /**
     * A cat clock, based on xclock's cat display mode.
     */
    interface Mew151XCatclock {
        /**
          * The color of the bowtie to display. Accepts any valid CSS colors, and possibly a few bonus ones.
          * @default '#a99cef'
         */
        "color"?: string;
    }
    /**
     * Renders cowsay in a "terminal"
     */
    interface Mew151XCowsay {
        /**
          * Replacement eyes for the cow
         */
        "eyes"?: string | undefined;
        /**
          * Replacement tongue for the cow
         */
        "mouth"?: string | undefined;
        /**
          * The text for the cow to say
          * @default 'Moo!'
         */
        "text"?: string;
    }
    /**
     * The main component that shows UNIX desktop toys on Mew151.net!
     */
    interface Mew151XRandom {
        /**
          * Odds of biblically accurate xeyes
          * @default 1 / 48
         */
        "biblicallyAccurateOdds"?: number;
        /**
          * Allows a page to force a specific desktop toy to appear
         */
        "forceSelection"?: ToyType | undefined;
        /**
          * Odds of getting a The Residents xeyes
          * @default 0
         */
        "residentOdds"?: number;
        /**
          * The color of the cat clock's tie
         */
        "tieColor"?: string | undefined;
    }
    interface Mew151XXeyes {
        /**
          * Whether the eyes are biblically accurate or not
          * @default false
         */
        "biblicallyAccurate"?: boolean;
        /**
          * The height of the canvas
         */
        "height"?: number;
        /**
          * Whether The Residents are watching or not
          * @default false
         */
        "theResidentsMode"?: boolean;
        /**
          * The width of the canvas
         */
        "width"?: number;
    }

    interface Mew151MewAttributes {
        "src": string;
        "alt": string;
    }
    interface Mew151XCatclockAttributes {
        "color": string;
    }
    interface Mew151XCowsayAttributes {
        "text": string;
        "eyes": string | undefined;
        "mouth": string | undefined;
    }
    interface Mew151XRandomAttributes {
        "forceSelection": ToyType | undefined;
        "biblicallyAccurateOdds": number;
        "residentOdds": number;
        "tieColor": string | undefined;
    }
    interface Mew151XXeyesAttributes {
        "biblicallyAccurate": boolean;
        "theResidentsMode": boolean;
        "width": number;
        "height": number;
    }

    interface IntrinsicElements {
        "mew151-mew": Omit<Mew151Mew, keyof Mew151MewAttributes> & { [K in keyof Mew151Mew & keyof Mew151MewAttributes]?: Mew151Mew[K] } & { [K in keyof Mew151Mew & keyof Mew151MewAttributes as `attr:${K}`]?: Mew151MewAttributes[K] } & { [K in keyof Mew151Mew & keyof Mew151MewAttributes as `prop:${K}`]?: Mew151Mew[K] };
        "mew151-prismstone-feed": Mew151PrismstoneFeed;
        "mew151-x-catclock": Omit<Mew151XCatclock, keyof Mew151XCatclockAttributes> & { [K in keyof Mew151XCatclock & keyof Mew151XCatclockAttributes]?: Mew151XCatclock[K] } & { [K in keyof Mew151XCatclock & keyof Mew151XCatclockAttributes as `attr:${K}`]?: Mew151XCatclockAttributes[K] } & { [K in keyof Mew151XCatclock & keyof Mew151XCatclockAttributes as `prop:${K}`]?: Mew151XCatclock[K] };
        "mew151-x-cowsay": Omit<Mew151XCowsay, keyof Mew151XCowsayAttributes> & { [K in keyof Mew151XCowsay & keyof Mew151XCowsayAttributes]?: Mew151XCowsay[K] } & { [K in keyof Mew151XCowsay & keyof Mew151XCowsayAttributes as `attr:${K}`]?: Mew151XCowsayAttributes[K] } & { [K in keyof Mew151XCowsay & keyof Mew151XCowsayAttributes as `prop:${K}`]?: Mew151XCowsay[K] };
        "mew151-x-random": Omit<Mew151XRandom, keyof Mew151XRandomAttributes> & { [K in keyof Mew151XRandom & keyof Mew151XRandomAttributes]?: Mew151XRandom[K] } & { [K in keyof Mew151XRandom & keyof Mew151XRandomAttributes as `attr:${K}`]?: Mew151XRandomAttributes[K] } & { [K in keyof Mew151XRandom & keyof Mew151XRandomAttributes as `prop:${K}`]?: Mew151XRandom[K] };
        "mew151-x-xeyes": Omit<Mew151XXeyes, keyof Mew151XXeyesAttributes> & { [K in keyof Mew151XXeyes & keyof Mew151XXeyesAttributes]?: Mew151XXeyes[K] } & { [K in keyof Mew151XXeyes & keyof Mew151XXeyesAttributes as `attr:${K}`]?: Mew151XXeyesAttributes[K] } & { [K in keyof Mew151XXeyes & keyof Mew151XXeyesAttributes as `prop:${K}`]?: Mew151XXeyes[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Component for the Mew sprites on the Mew151.net homepage. This handles the logic to swap out the image with the "shiny" equivalent sprite if the user is lucky enough.
             */
            "mew151-mew": LocalJSX.IntrinsicElements["mew151-mew"] & JSXBase.HTMLAttributes<HTMLMew151MewElement>;
            /**
             * Renders my fediverse feed fetched from an RSS feed.
             */
            "mew151-prismstone-feed": LocalJSX.IntrinsicElements["mew151-prismstone-feed"] & JSXBase.HTMLAttributes<HTMLMew151PrismstoneFeedElement>;
            /**
             * A cat clock, based on xclock's cat display mode.
             */
            "mew151-x-catclock": LocalJSX.IntrinsicElements["mew151-x-catclock"] & JSXBase.HTMLAttributes<HTMLMew151XCatclockElement>;
            /**
             * Renders cowsay in a "terminal"
             */
            "mew151-x-cowsay": LocalJSX.IntrinsicElements["mew151-x-cowsay"] & JSXBase.HTMLAttributes<HTMLMew151XCowsayElement>;
            /**
             * The main component that shows UNIX desktop toys on Mew151.net!
             */
            "mew151-x-random": LocalJSX.IntrinsicElements["mew151-x-random"] & JSXBase.HTMLAttributes<HTMLMew151XRandomElement>;
            "mew151-x-xeyes": LocalJSX.IntrinsicElements["mew151-x-xeyes"] & JSXBase.HTMLAttributes<HTMLMew151XXeyesElement>;
        }
    }
}
