/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    /**
     * Component for the Mew sprites on the Mew151.net homepage. This handles the logic to swap out the image with the "shiny" equivalent sprite if the user is lucky enough.
     */
    interface Mew151Mew {
        /**
          * Alt text to apply to the sprite.
         */
        "alt": string;
        /**
          * RNG function to determine if the Mew sprite is Shiny
          * @default () => this.calculateShinyOdds()
         */
        "isShiny": () => boolean;
        /**
          * The image source to be passed in.
         */
        "src": string;
    }
}
declare global {
    /**
     * Component for the Mew sprites on the Mew151.net homepage. This handles the logic to swap out the image with the "shiny" equivalent sprite if the user is lucky enough.
     */
    interface HTMLMew151MewElement extends Components.Mew151Mew, HTMLStencilElement {
    }
    var HTMLMew151MewElement: {
        prototype: HTMLMew151MewElement;
        new (): HTMLMew151MewElement;
    };
    interface HTMLElementTagNameMap {
        "mew151-mew": HTMLMew151MewElement;
    }
}
declare namespace LocalJSX {
    /**
     * Component for the Mew sprites on the Mew151.net homepage. This handles the logic to swap out the image with the "shiny" equivalent sprite if the user is lucky enough.
     */
    interface Mew151Mew {
        /**
          * Alt text to apply to the sprite.
         */
        "alt"?: string;
        /**
          * RNG function to determine if the Mew sprite is Shiny
          * @default () => this.calculateShinyOdds()
         */
        "isShiny"?: () => boolean;
        /**
          * The image source to be passed in.
         */
        "src"?: string;
    }

    interface Mew151MewAttributes {
        "src": string;
        "alt": string;
    }

    interface IntrinsicElements {
        "mew151-mew": Omit<Mew151Mew, keyof Mew151MewAttributes> & { [K in keyof Mew151Mew & keyof Mew151MewAttributes]?: Mew151Mew[K] } & { [K in keyof Mew151Mew & keyof Mew151MewAttributes as `attr:${K}`]?: Mew151MewAttributes[K] } & { [K in keyof Mew151Mew & keyof Mew151MewAttributes as `prop:${K}`]?: Mew151Mew[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Component for the Mew sprites on the Mew151.net homepage. This handles the logic to swap out the image with the "shiny" equivalent sprite if the user is lucky enough.
             */
            "mew151-mew": LocalJSX.IntrinsicElements["mew151-mew"] & JSXBase.HTMLAttributes<HTMLMew151MewElement>;
        }
    }
}
