name: Accessibility Tests

on:
  workflow_dispatch:

  workflow_call:

jobs:
  accessibility-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: "npm"

      - name: ⚙️ Install utilities
        run: npm ci --prefer-offline --verbose

      - name: 🍹 Build TypeScript / Sass
        run: npm run build

      - name: ✅ Run tests
        run: npm test
